import { Rubik } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar.js";
import ClientSessionProvider from "./components/clientSessionProvider";
import Footer from "./components/footer";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" >
        <body className={`${rubik.className}`}>
        <ClientSessionProvider>
        <div className="min-h-screen flex flex-col">
            <NavBar />
            <div className="flex-grow flex items-center justify-center"> 
              {children}
            </div>
            <Footer />
        </div>
        </ClientSessionProvider>
        </body>
      </html>
  );
}

//npm install @nextui-org/button
