import { Rubik } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar.js";
import ClientSessionProvider from "./components/clientSessionProvider";
import Footer from "./components/footer";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" className="h-full">
        <body className={`${rubik.className} h-full`}>
        <ClientSessionProvider>
        <div className="w-full h-full flex flex-col">
        <NavBar className="fixed top-0 w-full z-10" />
        <div className="flex-1 flex justify-center items-center mt-16"> 
          {children}
        </div>
        <Footer />
      </div>
        </ClientSessionProvider>
        </body>
      </html>
  );
}
